### ISSUE TITLE
Update to Rx 1.1.7 and integrate Single and other new types

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#1021]

**Comment by alkemist** [comment]
@tednaleid interested in looking at this one?

**Comment by tednaleid** [comment]
@alkemist yep, I can work on this

**Comment by tednaleid** [comment]
As part of this work, we'll want to update the `RxRatpack.initialize()` method so that it works properly with scripts that use the `@Grab` annotation to run ratpack.

In current scripts that use RxJava 1.1.2, using the `@Grab` annotation causes the `rx.Observable` class to get loaded in the classloader.  This causes the [static initializers to run and populate the `hook` field](https://github.com/ReactiveX/RxJava/blob/v1.1.2/src/main/java/rx/Observable.java#L63).  That happens before we have any chance to run `RxRatpack.initialize()` and registers the "wrong" execution hooks so groovy scripts are not fully ratpack aware.

This example script shows the issue using groovy 2.4.7:

```
@Grab('io.ratpack:ratpack-groovy:1.3.3')
@Grab('io.ratpack:ratpack-rx:1.3.3')

import ratpack.rx.RxRatpack
import static ratpack.groovy.Groovy.ratpack

RxRatpack.initialize()

ratpack {
  handlers {
    get { render "Hello World" }
  }
}
```

throws:

```
java.lang.IllegalStateException: Cannot install RxJava integration because another execution hook (class rx.plugins.RxJavaObservableExecutionHookDefault) is already installed
	at ratpack.rx.RxRatpack.initialize(RxRatpack.java:102)
	at ratpack.rx.RxRatpack$initialize.call(Unknown Source)
	at ConsoleScript0.run(ConsoleScript0:7)
```

So it has `RxJavaObservableExecutionHookDefault` installed (and unable to be overridden, instead of `rx.plugins.RxJavaSchedulersHook` that we want.

There are no public methods that enable the removal/resetting of this value, but in RxJava 1.1.7, this plugin system has been refactored to [delegate hooks](https://github.com/ReactiveX/RxJava/blob/v1.1.8/src/main/java/rx/Observable.java#L98) to a new [`RxJavaHooks`](https://github.com/ReactiveX/RxJava/blob/v1.1.8/src/main/java/rx/plugins/RxJavaHooks.java#L246) class that allows the app to `clear`, `reset`, and `lockdown` the hooks.

We'll want to refactor `RxRatpack.initialize()` so that it clears out the current hooks and registers the ratpack hooks.  Potentially then calling the `lockdown` method so that other processes don't override what we've done.

Some of this was figured out with the help of Paul King on a [Groovy JIRA that I filed](https://issues.apache.org/jira/browse/GROOVY-7896) when I didn't fully understand what was going on.

**Comment by beckje01** [comment]
Yeah we should call lockdown I think. Or make it an option of the initialize call.

**Comment by TimGundmann** [comment]
Work around in java
		Method method = RxJavaPlugins.class.getDeclaredMethod("reset");
		method.setAccessible(true);
		method.invoke(RxJavaPlugins.getInstance());
