### ISSUE TITLE
Failed to invoke get() on ServerCapturer

### ISSUE THREAD

**Issue by musikele** [ratpack/ratpack#1090]
Hi, 
when I run my project with `./gradlew -t run` (continuous build), I get the following error: 

```
./gradlew -t run
Continuous build is an incubating feature.
:compileJava UP-TO-DATE
:compileGroovy
Note: /Users/michelenasti/Tools/bemind/code/vidra.io/ms-pay/src/main/java/io/vidra/DbService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources UP-TO-DATE
:classes
:configureRun
:run
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/michelenasti/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.21/7238b064d1aba20da2ac03217d700d91e02460fa/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/michelenasti/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.12/42db62298b899818ff17352cbc00050e940bbfb0/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2016-10-24 14:57:35 DEBUG InternalLoggerFactory:71 - Using SLF4J as the default logging framework
2016-10-24 14:57:35 DEBUG ResourceLeakDetector:81 - -Dio.netty.leakDetection.level: simple
2016-10-24 14:57:35 DEBUG ResourceLeakDetector:81 - -Dio.netty.leakDetection.maxRecords: 4
2016-10-24 14:57:35 INFO  RatpackServer:105 - Starting server...
Unexpected exception thrown.
java.lang.RuntimeException: Failed to invoke get() on ServerCapturer
        at ratpack.gradle.continuous.run.RatpackServerProxy.capture(RatpackServerProxy.java:99)
        at ratpack.gradle.continuous.run.DefaultRatpackAdapter$1.run(DefaultRatpackAdapter.java:67)
        at ratpack.gradle.continuous.run.DefaultRatpackAdapter.inContext(DefaultRatpackAdapter.java:79)
        at ratpack.gradle.continuous.run.DefaultRatpackAdapter.reload(DefaultRatpackAdapter.java:64)
        at ratpack.gradle.continuous.run.DefaultRatpackAdapter.start(DefaultRatpackAdapter.java:49)
        at ratpack.gradle.continuous.run.RatpackAdapter$start.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at ratpack.gradle.continuous.run.RatpackWorkerServer.start(RatpackWorkerServer.groovy:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
> Building 83% > :run
```

My Gradle / Groovy version: 

```
./gradlew --version

------------------------------------------------------------
Gradle 2.9
------------------------------------------------------------

Build time:   2015-11-17 07:02:17 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_40 (Oracle Corporation 25.40-b25)
OS:           Mac OS X 10.12 x86_64
```

I'm using ratpack 1.4.3. Ideas? what can it be?

**Comment by alkemist** [comment]
This would mean that your server main method doesn't actually start a Ratpack server. What does your entry point look like?

**Comment by musikele** [comment]
My entry point is in groovy and is: 

```
ratpack {
  serverConfig {
    findBaseDir 'log4j.properties'
    env()
  }
  bindings {
    bindInstance(ServerErrorHandler, new ErrorHandler())
  } 
  handlers {
  ....
  }
}
``` 

I avoided the Handlers part, since I am still studying rat pack this is a bloated part. 

As I said you earlier, if I run `gradle run` no problem is spotted, while with `gradle -t run` I have the error I wrote you earlier.

**Comment by musikele** [comment]
Hi, I found the problem: 
` findBaseDir 'log4j.properties` does have no sense at all. I was using this method to search for the log4j file, but the method has other implications. 

Infact, once I removed that line, rat pack is working again. 

Thanks for patience.
