### ISSUE TITLE
RequestOutcome.getDuration throws NPE if never sent

### ISSUE THREAD

**Issue by jdbevan** [ratpack/ratpack#1185]
We've had a bunch of these errors in our logs:

```
request outcome listener ratpack.dropwizard.metrics.internal.DefaultRequestTimingHandler$$Lambda$220/814732403@518615d2 threw exception
java.lang.NullPointerException: temporal
	at java.util.Objects.requireNonNull(Objects.java:228)[:1.8.0_111]
	at java.time.Instant.from(Instant.java:371)[:1.8.0_111]
	at java.time.Instant.until(Instant.java:1144)[:1.8.0_111]
	at java.time.Duration.between(Duration.java:473)[:1.8.0_111]
	at ratpack.handling.RequestOutcome.getDuration(RequestOutcome.java:66)[application.jar:]
	at ratpack.dropwizard.metrics.internal.DefaultRequestTimingHandler.lambda$handle$0(DefaultRequestTimingHandler.java:46)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter.lambda$notifyListeners$7(DefaultResponseTransmitter.java:279)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListenerWithStackOverFlowProtection(DefaultPromise.java:457)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:416)[application.jar:]
	at io.netty.util.concurrent.CompleteFuture.addListener(CompleteFuture.java:49)[application.jar:]
	at io.netty.channel.CompleteChannelFuture.addListener(CompleteChannelFuture.java:56)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter.notifyListeners(DefaultResponseTransmitter.java:273)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter.post(DefaultResponseTransmitter.java:267)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter.post(DefaultResponseTransmitter.java:255)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter.access$100(DefaultResponseTransmitter.java:52)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter$1.cancel(DefaultResponseTransmitter.java:182)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter$1.lambda$$1(DefaultResponseTransmitter.java:176)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)[application.jar:]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:170)[application.jar:]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)[application.jar:]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)[application.jar:]
	at ratpack.server.internal.DefaultResponseTransmitter$1.onSubscribe(DefaultResponseTransmitter.java:204)[application.jar:]
	at ratpack.exec.internal.ExecutionBoundPublisher$1.lambda$onSubscribe$0(ExecutionBoundPublisher.java:69)[application.jar:]
	at ratpack.exec.internal.ExecutionBoundPublisher$1.dispatch(ExecutionBoundPublisher.java:55)[application.jar:]
	at ratpack.exec.internal.ExecutionBoundPublisher$1.onSubscribe(ExecutionBoundPublisher.java:68)[application.jar:]
	at ratpack.stream.internal.BufferingPublisher$BufferingSubscription.<init>(BufferingPublisher.java:155)[application.jar:]
	at ratpack.stream.internal.BufferingPublisher.subscribe(BufferingPublisher.java:59)[application.jar:]
	at ratpack.exec.internal.ExecutionBoundPublisher.lambda$subscribe$0(ExecutionBoundPublisher.java:43)[application.jar:]
	at ratpack.exec.internal.DefaultExecution$MultiEventExecStream.lambda$new$0(DefaultExecution.java:467)[application.jar:]
	at ratpack.exec.internal.DefaultExecution$MultiEventExecStream.exec(DefaultExecution.java:508)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:225)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:218)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.lambda$intercept$5(DefaultExecution.java:216)[application.jar:]
	at ratpack.logging.MDCInterceptor.intercept(MDCInterceptor.java:196)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:216)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.lambda$intercept$5(DefaultExecution.java:216)[application.jar:]
	at ratpack.dropwizard.metrics.internal.DefaultBlockingExecTimingInterceptor.intercept(DefaultBlockingExecTimingInterceptor.java:62)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:216)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:198)[application.jar:]
	at ratpack.exec.internal.DefaultExecution.access$300(DefaultExecution.java:43)[application.jar:]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.resume(DefaultExecution.java:440)[application.jar:]
	at ratpack.exec.internal.DefaultExecution$1.success(DefaultExecution.java:135)[application.jar:]
	at ratpack.http.client.internal.RequestActionSupport.success(RequestActionSupport.java:294)[application.jar:]
	at ratpack.http.client.internal.ContentStreamingRequestAction$Handler.channelRead0(ContentStreamingRequestAction.java:101)[application.jar:]
	at ratpack.http.client.internal.ContentStreamingRequestAction$Handler.channelRead0(ContentStreamingRequestAction.java:72)[application.jar:]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[application.jar:]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[application.jar:]
	at ratpack.http.client.internal.RequestActionSupport$1.channelRead0(RequestActionSupport.java:266)[application.jar:]
	at ratpack.http.client.internal.RequestActionSupport$1.channelRead0(RequestActionSupport.java:201)[application.jar:]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[application.jar:]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[application.jar:]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)[application.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)[application.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)[application.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)[application.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)[application.jar:]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[application.jar:]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)[application.jar:]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)[application.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)[application.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[application.jar:]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[application.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[application.jar:]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)[application.jar:]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)[application.jar:]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)[application.jar:]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)[application.jar:]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)[application.jar:]
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:136)[application.jar:]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)[application.jar:]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

which appear to be caused by a missing NPE check in the default `getDuration()` method on `RequestOutcome`.

**Comment by alkemist** [comment]
Thanks for the report.
