### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by sergey-morenets** [ratpack/ratpack#1221]
Hi

I am using JDK 9 (build 170, mixed mode) and tried to run Ratpack 1.4.6. I added VM arguments: --add-opens=java.base/java.nio=ALL-UNNAMED

However Ratpack server startup failed due to exception. Can you please help?

Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
	at ratpack.file.internal.ActivationBackedMimeTypes.<clinit>(ActivationBackedMimeTypes.java:34)
	at ratpack.server.internal.ServerRegistry.buildBaseRegistry(ServerRegistry.java:99)
	at ratpack.server.internal.ServerRegistry.serverRegistry(ServerRegistry.java:63)
	at ratpack.server.internal.DefaultRatpackServer.buildServerRegistry(DefaultRatpackServer.java:278)
	at ratpack.server.internal.DefaultRatpackServer.buildAdapter(DefaultRatpackServer.java:267)
	at ratpack.server.internal.DefaultRatpackServer$ReloadHandler.<init>(DefaultRatpackServer.java:393)
	at ratpack.server.internal.DefaultRatpackServer.buildHandler(DefaultRatpackServer.java:199)
	at ratpack.server.internal.DefaultRatpackServer.lambda$start$0(DefaultRatpackServer.java:119)
	at ratpack.exec.internal.ThreadBinding.bindFor(ThreadBinding.java:51)
	at ratpack.server.internal.DefaultRatpackServer.start(DefaultRatpackServer.java:119)
	at ratpack.server.RatpackServer.start(RatpackServer.java:90)
	at it.discovery.rest.ratpack.RatpackApplication.main(RatpackApplication.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:563)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:553)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:486)
	... 17 more

**Comment by michaelschlies** [comment]
The show stopper to the GA java 9 and executing ratpack upon it is an internal API that has moved and become properly exported. The internal API in question (ZipFileSystemProvider) has since been relocated from the JDK per jdeps below:
```
   ratpack.server.internal.BaseDirFinder              -> com.sun.nio.zipfs.ZipFileSystemProvider            JDK internal API (JDK removed internal API)
```
However, a new location within the jdk.zipfs platform module fills that need:
```
~$ java --describe-module jdk.zipfs
jdk.zipfs@9
requires java.base mandated
provides java.nio.file.spi.FileSystemProvider with jdk.nio.zipfs.ZipFileSystemProvider
contains jdk.nio.zipfs
```
This is the same aforementioned class causing issues with the OSGi issue listed above

**Comment by michaelschlies** [comment]
#1273 also covers some of the issues related to java9 and is worth checking out @sergey-morenets

**Comment by adamdougal** [comment]
Does anyone know if there are any workarounds for this? Just starting a new project and it'd be great to be able to use Ratpack and Java 9.

**Comment by michaelschlies** [comment]
I've been starting to port in a local branch to java9 modules but that's pushed me to do things like remove the gradle projects surrounding ratpack-site and ratpack-manual for now and split some things out into unique projects with external dependencies

**Comment by michaelschlies** [comment]
Not that I'd call this anywhere near production ready... but this is what I've been able to get done in the last 3 days or so...

![screenshot from 2017-12-20 22-56-49](https://user-images.githubusercontent.com/391345/34241214-8b9f43ca-e5d9-11e7-9d5b-bae9220ad660.png)

**Comment by michaelschlies** [comment]
There might be value in trying to snag some time from @ldaley or the like to see how one may make a concerted effort to roll this into a supported version, whether that becomes some of the core 2.x changes or what that might look like. I have a bunch of modules still to convert and for simplicity sake I was taking the module name and adding to the package path (i.e. ratpack.base.api, or ratpack.core.server) which should keep most of the tests working as expected so long as the packages get updated accordingly.

**Comment by jdbevan** [comment]
@michaelschlies is your branch available anywhere so we can help?

**Comment by michaelschlies** [comment]
I haven't pushed it public, but will probably look at doing so this week, was sort of hoping to coordinate it with the ratpack team a bit more, but I just pulled a fork for this and will CI it using JDK9 to address #1279 as well on Semaphore while I clean up some over-exported packages, etc.

**Comment by MichK21** [comment]
Guys, any progress on this? JDK 10 is already out...

**Comment by michaelschlies** [comment]
Lots of progress on this, except for the javax.annotations package conflicts between jsr305 and Spring -- so still in progress.

**Comment by jdbevan** [comment]
Is this going to be a problem? https://github.com/netty/netty/issues/6679

@michaelschlies can we help at all?

**Comment by jdbevan** [comment]
@michaelschlies any updates? I would like to help with this effort.

**Comment by KangoV** [comment]
Is there any movement on this one? I'm getting serious pressure to move to Spring Boot which I have resisted (for now) ;) But, I cannot hold the tigers off for long.

Just need to be able to give them a rough timeline....
Thanks.

**Comment by michaelschlies** [comment]
@KangoV You can use JDK >= 8 at this point with 1.6.0, but Ratpack itself isn't restructured to be built and published as java 9 modules yet. I know I am using 1.6.0 at work and home with JDK11.
