### ISSUE TITLE
Socket Close Exception in JMeter while testing ratpack app under load

### ISSUE THREAD

**Issue by zahid7292** [ratpack/ratpack#1242]
I am doing performance test of ratpack application using JMeter. Application is running fine initially but after about 5 minutes JMeter is reporting following exception:
```
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:158)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:271)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:209)
	at org.apache.jmeter.protocol.http.sampler.MeasuringConnectionManager$MeasuredConnection.receiveResponseHeader(MeasuringConnectionManager.java:212)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:654)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:413)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1166)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1155)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:475)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:418)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:249)
	at java.lang.Thread.run(Unknown Source)
```

System Configuration: 16GB RAM, 8 CPU.
Sample application can be found [here](https://github.com/zahid7292/testapp.git)

How to reproduce:
1. Start application.
2. Open  [testapp.jmx](https://github.com/zahid7292/testapp/blob/master/testapp.jmx) in JMeter and start testing
3. After about 5 minutes, request start failing. can be seen in right corner of jmeter

Thanks

**Comment by rhart** [comment]
What's happening with the server when the errors start? Are there any errors in the server logs?  Are response times increasing?

I would also give this a read https://wiki.apache.org/jmeter/JMeterSocketClosed

**Comment by zahid7292** [comment]
No error in server logs hence getting no clue what is happening.
I did already see this post and  enabled retry and stale check. But still getting the problem.

**Comment by zahid7292** [comment]
In server side I found this error in system.out 

`2017-07-14 13:53:47.107 [ratpack-compute-1-3] ERROR ratpack.server.internal.NettyHandlerAdapter  -
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_101]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_101]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_101]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_101]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_101]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.6.F
inal.jar:4.1.6.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.6.Final.jar:4.1.6.Fi
nal]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:366) ~[netty-transport-4.1.6.F
inal.jar:4.1.6.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) ~[netty-trans
port-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [netty-transport-4.1.6.Final.jar:
4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [netty-transport-4.1.6.
Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [netty-transport-4.1.6.Final.jar
:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.
1.6.Final.jar:4.1.6.Final]
        at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExec
Controller.java:136) [ratpack-core-1.4.5.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[n
etty-common-4.1.6.Final.jar:4.1.6.Final]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_101]
2017-07-14 13:53:47.107 [ratpack-compute-1-8] ERROR ratpack.server.internal.NettyHandlerAdapter  -
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_101]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_101]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_101]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_101]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_101]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.6.F
inal.jar:4.1.6.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.6.Final.jar:4.1.6.Fi
nal]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:366) ~[netty-transport-4.1.6.F
inal.jar:4.1.6.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) ~[netty-trans
port-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [netty-transport-4.1.6.Final.jar:
4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [netty-transport-4.1.6.
Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [netty-transport-4.1.6.Final.jar
:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.
1.6.Final.jar:4.1.6.Final]
        at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExec
Controller.java:136) [ratpack-core-1.4.5.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[n
etty-common-4.1.6.Final.jar:4.1.6.Final]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_101]`

**Comment by rhart** [comment]
That's because jmeter is terminating the connection.

I'm not convinced there is a Ratpack issue here as other Ratpack apps (doing a lot more) are taking much more load.  It seems like a jmeter/environment thing to me.

I will try running your setup when I get a chance.  In the meanwhile you could try:
- what happens if you reduce the load?
- what happens if you create your own sampler?
- do you get the issue using a proper load test setup i.e. different machines for client/server
- use a different load test tool, wrk2 or Gatling

**Comment by zahid7292** [comment]
- If I reduce load to 100 threads/users, error is thrown.
- I have created my own sampler only. [testapp.jmx](https://github.com/zahid7292/testapp/blob/master/testapp.jmx).
- I am running using proper load test setup i.e. different machines for client/server
- I am going to use Gatling/Loadrunner. 

I am also guessing it is client related. So I will use Galing/Loadrunner to verify that

**Comment by lshilleto** [comment]
@zahid7292 Have you tried the OS production tunings listed here: https://gist.github.com/danveloper/3440f151e44cfdda56040cc43890a1b9 
We faced a similar issues when load testing with JMeter. We have yet to test those tweaks but net.core.somaxconn and the ulimits look like they may help

**Comment by zahid7292** [comment]
This was Client side error. Client machine was running out of ephemeral ports, and hence was getting this exception. This Problem can be overcome either by increasing ephemeral ports or enabling (tcp_tw_reuse or tcp_tw_recycle). [increase ephemeral port on windows](https://msdn.microsoft.com/en-us/library/aa560610(v=bts.20).aspx) . [Article on tcp_tw_reuse, tcp_tw_recycle](https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux)

**Comment by rhart** [comment]
Thanks for the update @zahid7292

**Comment by Mehrasarthak** [comment]
I am getting below while recording for mobile application via Jmeter 5.0

javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.apache.jmeter.protocol.http.proxy.HttpRequestHdr.parse(HttpRequestHdr.java:138)
	at org.apache.jmeter.protocol.http.proxy.Proxy.run(Proxy.java:202)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(Unknown Source)
	... 8 more

Tried below:
1) httpclient4.retrycount=1
hc.parameters.file=hc.parameters
http.connection.stalecheck$Boolean=true

2) Different ports.
3) Valid certificate is installed on iOS device.

Please suggest.
