### ISSUE TITLE
Ratpack 1.5.0 with Hikari 2.6.2 errors when attempting to deserialize HikariConfig

### ISSUE THREAD

**Issue by mrobinet** [ratpack/ratpack#1270]
Minimal Ratpack application that reproduces the problem:
https://github.com/mrobinet/ratpack-hikari-1-5-0

Essentially if your app does something like this:
```
	serverConfig {
		yaml "ratpack-hikari.yml"
	}
	bindings {
		moduleConfig(HikariModule, serverConfig.get("/db", HikariConfig))
	}
```
...you get this error:
```
java.io.UncheckedIOException: com.fasterxml.jackson.databind.JsonMappingException: Can not find a deserializer for non-concrete Collection type [collection type; class java.util.concurrent.BlockingQueue, contains [simple type, class java.lang.Runnable]]
 at [Source: N/A; line: -1, column: -1]
	at ratpack.util.Exceptions.uncheck(Exceptions.java:52)
	at ratpack.config.internal.DefaultConfigData.getAsConfigObject(DefaultConfigData.java:62)
	at ratpack.config.ConfigData.getAsConfigObject(ConfigData.java:141)
	at ratpack.config.ConfigData.get(ConfigData.java:127)
	at ratpack.config.internal.DelegatingConfigData.get(DelegatingConfigData.java:38)
	at ratpack.config.ConfigData$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at ratpack$_run_closure1$_closure3.doCall(ratpack.groovy:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.runtime.ComposedClosure.call(ComposedClosure.java:104)
	at groovy.lang.Closure.call(Closure.java:430)
	at ratpack.groovy.internal.ClosureUtil.configure(ClosureUtil.java:65)
	at ratpack.groovy.internal.ClosureUtil.configureDelegateFirst(ClosureUtil.java:45)
	at ratpack.groovy.Groovy$Script.lambda$null$5(Groovy.java:346)
	at ratpack.guice.Guice.buildInjector(Guice.java:227)
	at ratpack.guice.Guice.registry(Guice.java:203)
	at ratpack.guice.Guice.lambda$registry$0(Guice.java:195)
	at ratpack.groovy.Groovy$Script.lambda$doApp$6(Groovy.java:347)
	at ratpack.server.internal.DefaultRatpackServer$DefinitionBuild.lambda$new$0(DefaultRatpackServer.java:165)
	at ratpack.server.internal.ServerRegistry.buildUserRegistry(ServerRegistry.java:75)
	at ratpack.server.internal.ServerRegistry.serverRegistry(ServerRegistry.java:64)
	at ratpack.server.internal.DefaultRatpackServer.buildServerRegistry(DefaultRatpackServer.java:286)
	at ratpack.server.internal.DefaultRatpackServer.buildAdapter(DefaultRatpackServer.java:275)
	at ratpack.server.internal.DefaultRatpackServer$ReloadHandler.lambda$null$2(DefaultRatpackServer.java:453)
	at ratpack.exec.Blocking$1.lambda$get$0(Blocking.java:70)
	at ratpack.exec.Blocking.intercept(Blocking.java:246)
	at ratpack.exec.Blocking.access$000(Blocking.java:35)
	at ratpack.exec.Blocking$1.get(Blocking.java:68)
	at ratpack.exec.Blocking$1.get(Blocking.java:61)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:136)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not find a deserializer for non-concrete Collection type [collection type; class java.util.concurrent.BlockingQueue, contains [simple type, class java.lang.Runnable]]
 at [Source: N/A; line: -1, column: -1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:305)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:443)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:964)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:498)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:443)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:964)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:498)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3765)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2165)
	at ratpack.config.internal.DefaultConfigData.getAsConfigObject(DefaultConfigData.java:59)
	... 43 more
Caused by: java.lang.IllegalArgumentException: Can not find a deserializer for non-concrete Collection type [collection type; class java.util.concurrent.BlockingQueue, contains [simple type, class java.lang.Runnable]]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:1022)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:391)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 62 more
```

**Comment by mrobinet** [comment]
Workaround for this issue is to deserialize config to a Properties object and use it to manually construct the HikariConfig:
```
Properties hikariConfigProperties = serverConfig.get("/db", Properties)
moduleConfig(HikariModule, new HikariConfig(hikariConfigProperties))
```

**Comment by ldaley** [comment]
I'm going to close this off. Transparently fixing would require adding a Jackson mapping to BlockingQueue, which users can do themselves.

**Comment by KangoV** [comment]
> I'm going to close this off. Transparently fixing would require adding a Jackson mapping to BlockingQueue, which users can do themselves.

What do you mean by add a binding?
