### ISSUE TITLE
HttpClient throws UnsupportedOperationException in 1.5.1 with EPoll

### ISSUE THREAD

**Issue by jansyk13** [ratpack/ratpack#1317]
After updating to 1.5.1 from 1.5.0, we are having issues with HttpClient throwing exception when sending request with body (not 100% about when it occurs). It happens only when using Epoll (on Centos 7.3.1611), after I tried to switch to NIO, it seems to work.  Anyone running into same issues?

I will try to provide working reproducer and go through commits that were new for 1.5.1.

```
io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
	at io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:641)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:948)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:543)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1321)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at ratpack.http.client.internal.RequestActionSupport.lambda$send$4(RequestActionSupport.java:137)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenerWithStackOverFlowProtection(DefaultPromise.java:450)
	at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:409)
	at io.netty.util.concurrent.CompleteFuture.addListener(CompleteFuture.java:49)
	at io.netty.channel.CompleteChannelFuture.addListener(CompleteChannelFuture.java:56)
	at io.netty.channel.CompleteChannelFuture.addListener(CompleteChannelFuture.java:27)
	at ratpack.http.client.internal.RequestActionSupport.send(RequestActionSupport.java:135)
	at ratpack.http.client.internal.RequestActionSupport.lambda$null$0(RequestActionSupport.java:99)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:136)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: null
	at io.netty.buffer.FixedCompositeByteBuf.memoryAddress(FixedCompositeByteBuf.java:635)
	at io.netty.buffer.ReadOnlyByteBuf.memoryAddress(ReadOnlyByteBuf.java:121)
	at io.netty.channel.unix.IovArray.add(IovArray.java:94)
	at io.netty.channel.unix.IovArray.processMessage(IovArray.java:209)
	at io.netty.channel.ChannelOutboundBuffer.forEachFlushedMessage(ChannelOutboundBuffer.java:738)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:500)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:442)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:543)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1321)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at ratpack.http.client.internal.RequestActionSupport.lambda$send$4(RequestActionSupport.java:137)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenerWithStackOverFlowProtection(DefaultPromise.java:450)
	at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:409)
	at io.netty.util.concurrent.CompleteFuture.addListener(CompleteFuture.java:49)
	at io.netty.channel.CompleteChannelFuture.addListener(CompleteChannelFuture.java:56)
	at io.netty.channel.CompleteChannelFuture.addListener(CompleteChannelFuture.java:27)
	at ratpack.http.client.internal.RequestActionSupport.send(RequestActionSupport.java:135)
	at ratpack.http.client.internal.RequestActionSupport.lambda$null$0(RequestActionSupport.java:99)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

```

**Comment by jenschude** [comment]
Have the same issue, but inside a docker container running on alpine. Fixed it by downgrading to ratpack 1.5.0.

Maybe related to the netty issue mentioned in #1295

**Comment by jansyk13** [comment]
@ldaley @jenschude Would it be possible to downgrade Netty version? Most people run their applications on Linux based envs with epoll. So this is basically blocker for updating. The issue in Netty might take long to fix and propagate.

**Comment by ldaley** [comment]
Hi @jansyk13 I intend to release 1.5.2 with Netty 4.1.19 or 4.1.21 if it comes out today.

In the meantime, you can roll back the Netty version change in 1.5.1 through your build tool.

**Comment by ldaley** [comment]
I've raised an issue against Netty for this problem: https://github.com/netty/netty/issues/7752

@jansyk13 @jenschude this will only happen with a certain kind of buffer for the request body, I think. Is it possible that you are using composite buffers to form the request body? If so, a workaround would be to copy to a non-composite buffer and use that.

**Comment by jansyk13** [comment]
Cool, thanks for investigating. I looked into where the composite byte buf is created and it is in `RequestBody`.
```
private ByteBuf composeReceived() {
    if (received.isEmpty()) {
      return Unpooled.EMPTY_BUFFER;
    } else {
      ByteBuf[] byteBufsArray = this.received.toArray(new ByteBuf[this.received.size()]);
      received.clear();
      return Unpooled.unmodifiableBuffer(byteBufsArray);
    }
  }
```

**Comment by jenschude** [comment]
We are proxying incoming request from an API to send it to another API.

```
private static class RequestProxyHandler implements Handler {

        @Override
        public void handle(final Context ctx) throws Exception {
            final Request request = ctx.getRequest();
            final TypedData body = ctx.get(TypedData.class);
            final HttpClient httpClient = ctx.get(HttpClient.class);
            ...
            httpClient.request(proxiedUri, proxyRequest(body, request, insecureSSL))
                    .then(receivedResponse ->
                            ctx.next(Registry.builder().add(receivedResponse).add(proxiedUri).build()));
        }

        private Action<RequestSpec> proxyRequest(final TypedData body, final Request request, final Boolean insecureSSL) {
            return spec -> {
                if (insecureSSL) {
                    spec.sslContext(SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build());
                }
                spec.getBody().buffer(body.getBuffer());
                spec.getHeaders().copy(request.getHeaders());
                spec.method(request.getMethod());
            };
        }
    }
```

**Comment by jansyk13** [comment]
@ldaley I think the issue is how the `IovArray` in Netty is implemented now. Previously it seems that it has used nio buffers to copy it into direct memory. https://github.com/netty/netty/commit/3c4dfed08ae2ce300f6ac1d0794d42a14c344b79#diff-0e9057048e953cd92a9fa1fca027244c

**Comment by jansyk13** [comment]
To be exact, I think this change broke it. https://github.com/netty/netty/commit/3c4dfed08ae2ce300f6ac1d0794d42a14c344b79#diff-0e9057048e953cd92a9fa1fca027244cL216

**Comment by ldaley** [comment]
@jenschude a workaround would be to copy the request body buffer to a new buffer and send that instead.

**Comment by jansyk13** [comment]
@jenschude @ldaley I think copying might have too big performance impact, little bit hacky solution would be to add an empty byte buf to the end of composite byte buf when there is only one buf inside the composite one. I think it would work

@ldaley I looked into issue you created in Netty, I would a create a PR with fix for that if you don't mind, ok? I think the solution with `buf.hasMemoryAddress()` is much cleaner than the modifying `memoryAddress()` for composite byte buf with single buf.

**Comment by ldaley** [comment]
@jansyk13 I have added a workaround (which is a good change in of itself) in Ratpack: https://github.com/ratpack/ratpack/commit/f4bba4b8228ea756d17d84963189699aa1a9d50a

I will release this as 1.5.3, which I am doing now.

**Comment by ldaley** [comment]
@jansyk13 @jenschude There was a bug in 1.5.3 in this area. You'll have to use 1.5.4.

**Comment by jenschude** [comment]
@ldaley yeah tried it yesterday and got some new exception, didn't had the time to report it. With 1.5.4 it's working now 👍
