### ISSUE TITLE
Error with 1.6.0-rc-1 and Java 11.0.1

### ISSUE THREAD

**Issue by lwolter** [ratpack/ratpack#1410]
Error occurs directly at startup. The application starts anyway. I use groovy 2.5.4. With Java 8, the problem does not occur.

11:04:44.477 [main]            DEBUG i.n.u.i.PlatformDependent0 - -Dio.netty.noUnsafe: false
11:04:44.477 [main]            DEBUG i.n.u.i.PlatformDependent0 - Java version: 11
11:04:44.479 [main]            DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
11:04:44.479 [main]            DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
11:04:44.480 [main]            DEBUG i.n.u.i.PlatformDependent0 - java.nio.Buffer.address: available
11:04:44.483 [main]            DEBUG i.n.u.i.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
        at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
        at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:212)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:80)
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
        at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
        at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
        at ratpack.server.internal.DefaultRatpackServer.<clinit>(DefaultRatpackServer.java:69)
        at ratpack.server.RatpackServer.of(RatpackServer.java:81)
        at ratpack.server.RatpackServer.start(RatpackServer.java:92)
        at ratpack.groovy.GroovyRatpackMain.main(GroovyRatpackMain.java:38)
11:04:44.484 [main]            DEBUG i.n.u.i.PlatformDependent0 - java.nio.Bits.unaligned: available, true
11:04:44.485 [main]            DEBUG i.n.u.i.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @366647c2
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
        at java.base/java.lang.reflect.Method.invoke(Method.java:558)
        at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:325)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:212)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:80)
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
        at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
        at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
        at ratpack.server.internal.DefaultRatpackServer.<clinit>(DefaultRatpackServer.java:69)
        at ratpack.server.RatpackServer.of(RatpackServer.java:81)
        at ratpack.server.RatpackServer.start(RatpackServer.java:92)
        at ratpack.groovy.GroovyRatpackMain.main(GroovyRatpackMain.java:38)
11:04:44.485 [main]            DEBUG i.n.u.i.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
11:04:44.485 [main]            DEBUG i.n.u.internal.PlatformDependent - sun.misc.Unsafe: available

**Comment by johnrengelman** [comment]
This is related to https://github.com/netty/netty/issues/7769. You can find workarounds there, but this is just a debug statement and shouldn't impact the running application from what I can tell.

**Comment by ehiggs** [comment]
Doesn't this mean that ByteBuf cannot allocate uninitialized memory, hence having performance implications when using unpooled byte buffers? 
``` 11:04:44.485 [main] DEBUG i.n.u.i.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable```

**Comment by lwolter** [comment]
I have no deeper knowledge here. However, the error was bypassed with the following parameters:
`--add-exports "java.base/jdk.internal.misc=ALL-UNNAMED" 
"-Dio.netty.tryReflectionSetAccessible=true"`
