### ISSUE TITLE
RatpackRetrofitCallException throws exception when response contains error body

### ISSUE THREAD

**Issue by rogerpereira123** [ratpack/ratpack#1456]
If the Retrofit error response contains body, `RatpackRetrofitCallException` throws IOException:

```
java.io.UncheckedIOException: java.io.IOException: Content-Length (5) and stream length (0) disagree
        at ratpack.util.Exceptions.uncheck(Exceptions.java:52)
        at ratpack.util.Exceptions.uncheck(Exceptions.java:105)
        at ratpack.retrofit.RatpackRetrofitCallException.getResponse(RatpackRetrofitCallException.java:75)
        at ratpack.retrofit.RatpackRetrofitCallException$getResponse.call(Unknown Source)
``` 

Snippet to reproduce:

```groovy
@Grapes([
  @Grab('io.ratpack:ratpack-groovy:1.6.1'),
  @Grab('org.slf4j:slf4j-simple:1.7.25'),
  @Grab('io.ratpack:ratpack-retrofit2:1.6.1'),
  @Grab('io.ratpack:ratpack-test:1.6.1'),
  @Grab('io.ratpack:ratpack-groovy-test:1.6.1')
 ])
import ratpack.exec.Promise
import ratpack.retrofit.RatpackRetrofit
import ratpack.groovy.test.embed.GroovyEmbeddedApp
import retrofit2.http.GET
import ratpack.guice.Guice
import ratpack.retrofit.RatpackRetrofitCallException
import static org.junit.Assert.*


 public interface HelloApi {
   @GET("hi") Promise<String> hello()
 }

 def api = GroovyEmbeddedApp.of  {
      handlers {
        get("hi")  {
            //render("hello")
            response.status(500).send("error")
        }
      } 
 } 

 GroovyEmbeddedApp.of {
     registry Guice.registry {
                it.bindInstance(HelloApi.class,
         RatpackRetrofit
           .client(api.getAddress())
           .build(HelloApi.class))
      }
    handlers { 
           get { ctx ->
               HelloApi helloApi = ctx.get(HelloApi.class)
               helloApi.hello()
               .onError {
                   if(it instanceof RatpackRetrofitCallException) {
                       render(it.getResponse().getStatusCode().toString())
                   }
               }
               .then {
                   render(it)
               }
           }
       }
 } test { httpClient ->
       println("Retrofit API Response: " + httpClient.getText())
     api.close()
   }  
```

**Comment by drmaas** [comment]
@rogerpereira123 This can be closed as the PR was merged.
