### ISSUE TITLE
Update Guice version

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#1557]
Guice 4.1 has issues when logging errors from binding failures when running on Java 9+.

This results in a log message that doesn't indicate the actual Guice binding failure and instead logs an generic `IllegalArgumentException`:

```
Caused by: java.lang.IllegalArgumentException
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:66)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:46)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:43)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
```

See https://github.com/playframework/playframework/issues/8268

https://github.com/ratpack/ratpack/blob/master/gradle/dependencies.gradle#L33

**Comment by johnrengelman** [comment]
Updated in https://github.com/ratpack/ratpack/pull/1558
