### ISSUE TITLE
Error with simple script example

### ISSUE THREAD

**Issue by AxelRHD** [ratpack/ratpack#1570]
I was just trying out Ratpack the first time, getting the following error (even on a freshly installed machine):

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-swing is loaded in version 3.0.4 and you are trying to load version 2.5.4

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-swing is loaded in version 3.0.4 and you are trying to load version 2.5.4
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerExtensionModuleFromProperties(MetaClassRegistryImpl.java:168)
	at groovy.grape.GrapeIvy.processCategoryMethods(GrapeIvy.groovy:329)
	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:282)
	at groovy.grape.Grape$1.run(Grape.java:174)
	at groovy.grape.Grape$1.run(Grape.java:160)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at groovy.grape.Grape.grab(Grape.java:160)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:377)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:650)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
	at groovy.lang.GroovyShell.run(GroovyShell.java:359)
	at groovy.lang.GroovyShell.run(GroovyShell.java:349)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:398)
	at groovy.ui.GroovyMain.access$1400(GroovyMain.java:68)
	at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:322)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:142)
	at groovy.ui.GroovyMain.main(GroovyMain.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:111)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:129)

1 error
```

All Java-relevant programs are installed with sdkman.

Java version: 11.0.9.hs-adpt
Groovy version: 3.0.4

Content of ratpack.groovy:

```groovy
@Grab('io.ratpack:ratpack-groovy:1.8.0')

import static ratpack.groovy.Groovy.ratpack

ratpack {
        handlers {
                get {
                        render "Hello World!"
                }
        }
}
```

I can't figure out, where this conflict of the modules comes from.

**Comment by bsnux** [comment]
Seeing this error with same code. Different JDK version:

```
➜  /tmp java --version
openjdk 11.0.6 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
➜  /tmp groovy --version
Groovy Version: 3.0.4 JVM: 11.0.6 Vendor: Oracle Corporation OS: Linux
```

**Comment by bsnux** [comment]
I fixed the error adding this:

`@Grab(group='io.ratpack', module='ratpack-groovy', version='1.8.0',  transitive=false)
`

**Comment by ldaley** [comment]
@bsnux Ratpack 1.8 is not compatible with Groovy 3. The upcoming 2.x version will be.
