### ISSUE TITLE
HikariConfig can not be deserialized by Jackson for Config

### ISSUE THREAD

**Issue by jwshin** [ratpack/ratpack#1591]
HikariConfig has been marked invalid subtype per https://github.com/FasterXML/jackson-databind/issues/2631 and can not be deserialized by Jackson for use during server configuration.  I can submit a PR to work around it (perhaps a internal proxy of HikariConfig to be used by HikariModule) but is there a preference on approach?

Exception below:

`java.lang.IllegalStateException: Failed to build required config items
        at ratpack.server.internal.DefaultServerConfigBuilder.extractRequiredConfig(DefaultServerConfigBuilder.java:414)
        at ratpack.server.internal.DefaultServerConfigBuilder.build(DefaultServerConfigBuilder.java:409)
        at ratpack.server.RatpackServerSpec.serverConfig(RatpackServerSpec.java:89)
        at ratpack.groovy.Groovy$Script.doApp(Groovy.java:341)
        at ratpack.groovy.Groovy$Script.lambda$appWithArgs$4(Groovy.java:333)
        at ratpack.server.internal.RatpackServerDefinition.build(RatpackServerDefinition.java:43)
        at ratpack.server.internal.DefaultRatpackServer.lambda$buildUserDefinition$4(DefaultRatpackServer.java:216)
        at ratpack.impose.Impositions.impose(Impositions.java:117)
        at ratpack.server.internal.DefaultRatpackServer.buildUserDefinition(DefaultRatpackServer.java:214)
        at ratpack.server.internal.DefaultRatpackServer.start(DefaultRatpackServer.java:117)
        at ratpack.server.RatpackServer.start(RatpackServer.java:93)
        at ratpack.groovy.GroovyRatpackMain.main(GroovyRatpackMain.java:38)
        Suppressed: java.lang.IllegalStateException: Could not bind config at '/hikari' to 'com.zaxxer.hikari.HikariConfig'
                at ratpack.server.internal.DefaultServerConfigBuilder.extractRequiredConfig(DefaultServerConfigBuilder.java:422)
                ... 11 more
        Caused by: java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `com.zaxxer.hikari.HikariConfig`: Illegal type (com.zaxxer.hikari.HikariConfig) to deserialize: prevented for security reasons
 at [Source: UNKNOWN; line: -1, column: -1]
                at ratpack.util.Exceptions.uncheck(Exceptions.java:52)
                at ratpack.config.internal.DefaultConfigData.getAsConfigObject(DefaultConfigData.java:62)
                at ratpack.server.internal.DefaultServerConfigBuilder.extractRequiredConfig(DefaultServerConfigBuilder.java:420)
                ... 11 more
        Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `com.zaxxer.hikari.HikariConfig`: Illegal type (com.zaxxer.hikari.HikariConfig) to deserialize: prevented for security reasons
 at [Source: UNKNOWN; line: -1, column: -1]
                at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
                at com.fasterxml.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1570)
                at com.fasterxml.jackson.databind.jsontype.impl.SubTypeValidator.validateSubType(SubTypeValidator.java:195)
                at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._validateSubType(BeanDeserializerFactory.java:925)
                at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
                at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
                at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
                at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
                at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:479)
                at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4405)
                at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4184)
                at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2545)
                at ratpack.config.internal.DefaultConfigData.getAsConfigObject(DefaultConfigData.java:59)
                ... 12 more`

**Comment by ldaley** [comment]
Hi @jwshin. Thanks for reporting.

Do you know what it's actually objecting to about this type?

**Comment by ldaley** [comment]
Here's the root cause: http://b1ue.cn/archives/201.html

**Comment by ldaley** [comment]
Will have to resolved in 2.0 as it requires a breaking change of not mapping HikariConfig as a config item.

**Comment by jwshin** [comment]
Sorry for late follow up.  Thanks for looking into this.

**Comment by johnrengelman** [comment]
So, this is the same vector as the recent Log4j attacks which is because the `HikariConfig` class is doing JNDI lookup in the `setMetricRegistry` method. I browsed their repo and haven't found any issues or PRs that are attempting to address this (which seems to be why Jackson directly blocked the class as a deserialization target).
