### ISSUE TITLE
StackOverflowError when hitting a dev error page with Accept header other than html/plainText

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#548]
I first encountered this with the dev error page.  I'll see if it also applies to the normal error handler.

```
Error handler throwable: java.lang.StackOverflowError
	at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:691)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:271)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.PrintStream.write(PrintStream.java:526)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:381)
	at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:376)
	at org.slf4j.impl.SimpleLogger.error(SimpleLogger.java:622)
	at ratpack.error.internal.DefaultDevelopmentErrorHandler.error(DefaultDevelopmentErrorHandler.java:81)
	at ratpack.handling.internal.DefaultContext.clientError(DefaultContext.java:418)
	at ratpack.http.internal.ContentNegotiationHandler.handle(ContentNegotiationHandler.java:55)
	at ratpack.handling.internal.DefaultContext.byContent(DefaultContext.java:435)
	at ratpack.error.internal.DefaultDevelopmentErrorHandler.error(DefaultDevelopmentErrorHandler.java:84)
	at ratpack.handling.internal.DefaultContext.clientError(DefaultContext.java:418)
	at ratpack.http.internal.ContentNegotiationHandler.handle(ContentNegotiationHandler.java:55)
	at ratpack.handling.internal.DefaultContext.byContent(DefaultContext.java:435)
	at ratpack.error.internal.DefaultDevelopmentErrorHandler.error(DefaultDevelopmentErrorHandler.java:84)
	at ratpack.handling.internal.DefaultContext.clientError(DefaultContext.java:418)
	at ratpack.http.internal.ContentNegotiationHandler.handle(ContentNegotiationHandler.java:55)
	at ratpack.handling.internal.DefaultContext.byContent(DefaultContext.java:435)
	at ratpack.error.internal.DefaultDevelopmentErrorHandler.erroltDevelopmentErrorHandler.java:84)
	at ratpack.handling.internal.DefaultContext.clientError(DefaultContext.java:418)
...
```

**Comment by davidmc24** [comment]
Appears to apply only to dev error page.

**Comment by davidmc24** [comment]
The default development error handler will now return plain text for any requested content type that doesn't match text/html.
