### ISSUE TITLE
Using @CompileStatic on Modules defined as groovy classes results in guice exception

### ISSUE THREAD

**Issue by kyleboon** [ratpack/ratpack#581]
This worked as of 0.9.11 but in 0.9.13 you cannot statically compile modules.

```
2015-02-08 16:21:44,260 ERROR r.e.i.DefaultDevelopmentErrorHandler [ratpack-compute-1-2] exception thrown for request to /api/book java.lang.NullPointerException
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:203)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:169)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
	at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96)
	at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
	at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1163)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3290)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3288)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3264)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:251)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:872)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:230)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:234)
	at ratpack$_run_closure1$_closure2.doCall(ratpack.groovy:48)
```

I recreated this in the example-book project. You can see it here: https://github.com/kyleboon/example-books/compare/ratpack:master...master

**Comment by alkemist** [comment]
It will be due to the groovy version change.

We aren't requiring anything from 2.4, so you can just force use of 2.3.9 to unblock.

**Comment by davidmc24** [comment]
The issue in the Groovy tracker is https://jira.codehaus.org/browse/GROOVY-7278.

Unfortunately, using Groovy 2.3.9 in some cases would require bypassing GroovyVersionCheck... somehow.

**Comment by alkemist** [comment]
Good point re the Groovy version check.

**Comment by kyleboon** [comment]
It's fine for me to just not use @CompileStatic on those classes so its not a big issue for me - more just something people might run into when upgrading existing applications

**Comment by davidmc24** [comment]
Also... I think this bug was introduced in 2.3.7, so you'd need to go back to 2.3.6.

**Comment by kyleboon** [comment]
Should we just close this?

**Comment by davidmc24** [comment]
My inclination is to leave it open until GROOVY-7278 is resolved and released... and close it when we upgrade to a version of Groovy that isn't affected.

**Comment by alkemist** [comment]
@davidmc24 +1
