### ISSUE TITLE
ratpack-site's /versions handler fails on bad response from github

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#601]
Exception appears to be:```
2015-03-07T16:48:17.249232+00:00 app[web.1]:  java.lang.RuntimeException: Not an array response from https://api.github.com/repos/ratpack/ratpack/milestones?state=open&sort=due_date&direction=asc&per_page=100
2015-03-07T16:48:17.249237+00:00 app[web.1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-03-07T16:48:17.249255+00:00 app[web.1]: 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
2015-03-07T16:48:17.249258+00:00 app[web.1]: 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
2015-03-07T16:48:17.249238+00:00 app[web.1]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
2015-03-07T16:48:17.249235+00:00 app[web.1]: 	at sun.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)
2015-03-07T16:48:17.249242+00:00 app[web.1]: 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
2015-03-07T16:48:17.249244+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
2015-03-07T16:48:17.249245+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
2015-03-07T16:48:17.249252+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-03-07T16:48:17.249274+00:00 app[web.1]: 	at ratpack.rx.RxRatpack$$Lambda$159/1538871512.call(Unknown Source)
2015-03-07T16:48:17.249247+00:00 app[web.1]: 	at ratpack.site.github.GithubRequester$_getPage_closure4.doCall(GithubRequester.groovy:64)
2015-03-07T16:48:17.249249+00:00 app[web.1]: 	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
2015-03-07T16:48:17.249250+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-03-07T16:48:17.249240+00:00 app[web.1]: 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
2015-03-07T16:48:17.249264+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:103)
2015-03-07T16:48:17.249284+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle$$Lambda$179/119570212.execute(Unknown Source)
2015-03-07T16:48:17.249319+00:00 app[web.1]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
2015-03-07T16:48:17.249253+00:00 app[web.1]: 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
2015-03-07T16:48:17.249287+00:00 app[web.1]: 	at ratpack.exec.internal.InterceptedOperation.run(InterceptedOperation.java:46)
2015-03-07T16:48:17.249320+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-07T16:48:17.249260+00:00 app[web.1]: 	at groovy.lang.Closure.call(Closure.java:423)
2015-03-07T16:48:17.249262+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51)
2015-03-07T16:48:17.249269+00:00 app[web.1]: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
2015-03-07T16:48:17.249272+00:00 app[web.1]: 	at ratpack.rx.RxRatpack.lambda$observe$2(RxRatpack.java:192)
2015-03-07T16:48:17.249291+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking.access$000(ExecutionBacking.java:38)
2015-03-07T16:48:17.249295+00:00 app[web.1]: 	at ratpack.exec.internal.SafeFulfiller.success(SafeFulfiller.java:78)
2015-03-07T16:48:17.249257+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
2015-03-07T16:48:17.249265+00:00 app[web.1]: 	at com.sun.proxy.$Proxy47.call(Unknown Source)
2015-03-07T16:48:17.249280+00:00 app[web.1]: 	at ratpack.exec.internal.SafeFulfiller.lambda$success$192(SafeFulfiller.java:78)
2015-03-07T16:48:17.249294+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle.complete(ExecutionBacking.java:110)
2015-03-07T16:48:17.249270+00:00 app[web.1]: 	at ratpack.rx.RxRatpack$ExecutionBackedSubscriber.onNext(RxRatpack.java:506)
2015-03-07T16:48:17.249275+00:00 app[web.1]: 	at ratpack.rx.RxRatpack$PromiseSubscribe.lambda$call$11(RxRatpack.java:449)
2015-03-07T16:48:17.249290+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking.drain(ExecutionBacking.java:172)
2015-03-07T16:48:17.249283+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle.lambda$complete$185(ExecutionBacking.java:112)
2015-03-07T16:48:17.249292+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle.streamEvent(ExecutionBacking.java:120)
2015-03-07T16:48:17.249301+00:00 app[web.1]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2015-03-07T16:48:17.249278+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultSuccessPromise$UserActionFulfiller.success(DefaultSuccessPromise.java:280)
2015-03-07T16:48:17.249286+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$1.performOperation(ExecutionBacking.java:221)
2015-03-07T16:48:17.249348+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-07T16:48:17.249281+00:00 app[web.1]: 	at ratpack.exec.internal.SafeFulfiller$$Lambda$178/1887750195.execute(Unknown Source)
2015-03-07T16:48:17.249391+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
2015-03-07T16:48:17.249322+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-07T16:48:17.249267+00:00 app[web.1]: 	at rx.Observable$31.onNext(Observable.java:7139)
2015-03-07T16:48:17.249277+00:00 app[web.1]: 	at ratpack.rx.RxRatpack$PromiseSubscribe$$Lambda$161/1549209343.execute(Unknown Source)
2015-03-07T16:48:17.249288+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking.intercept(ExecutionBacking.java:223)
2015-03-07T16:48:17.249296+00:00 app[web.1]: 	at ratpack.http.client.internal.RequestActionSupport.success(RequestActionSupport.java:205)
2015-03-07T16:48:17.249350+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
2015-03-07T16:48:17.249385+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-07T16:48:17.249308+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-07T16:48:17.249382+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-07T16:48:17.249300+00:00 app[web.1]: 	at ratpack.http.client.internal.ContentAggregatingRequestAction$1.channelRead0(ContentAggregatingRequestAction.java:49)
2015-03-07T16:48:17.249298+00:00 app[web.1]: 	at ratpack.http.client.internal.ContentAggregatingRequestAction$1.channelRead0(ContentAggregatingRequestAction.java:58)
2015-03-07T16:48:17.249370+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-07T16:48:17.249384+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-07T16:48:17.249374+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-07T16:48:17.249393+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
2015-03-07T16:48:17.249398+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$166(DefaultExecController.java:82)
2015-03-07T16:48:17.249311+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-07T16:48:17.249377+00:00 app[web.1]: 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:929)
2015-03-07T16:48:17.249387+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:947)
2015-03-07T16:48:17.249310+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-07T16:48:17.249399+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory$$Lambda$117/1956602275.run(Unknown Source)
2015-03-07T16:48:17.249312+00:00 app[web.1]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2015-03-07T16:48:17.249314+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-07T16:48:17.249401+00:00 app[web.1]: 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-03-07T16:48:17.249375+00:00 app[web.1]: 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1044)
2015-03-07T16:48:17.249379+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:315)
2015-03-07T16:48:17.249402+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745)
2015-03-07T16:48:17.249395+00:00 app[web.1]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
2015-03-07T16:48:17.249317+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-07T16:48:17.249372+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-07T16:48:17.249388+00:00 app[web.1]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
2015-03-07T16:48:17.249380+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:229)
2015-03-07T16:48:17.249389+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
2015-03-07T16:48:17.249394+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
2015-03-07T16:48:17.249316+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)```

This results in subsequent requests to http://www.ratpack.io/versions going to a heroku error page, with a log entry of `2015-03-07T16:50:32.699275+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/versions" host=www.ratpack.io request_id=de42e071-0b36-4949-b090-19fc9f9760df fwd="50.31.164.139" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0`

**Comment by davidmc24** [comment]
This appears to have hit again today.  An error was encountered processing GitHub's API response at 2015-03-16T11:00:03.953156+00:00, and then requests for `/version` timed out until 2015-03-16T11:51:42.549159+00:00 (no manual intervention involved that I know of).  Perhaps the right think to do is just cache the last successful result from the GitHub API?

```
2015-03-16T11:00:03.953156+00:00 app[web.1]: 2015-03-16 11:00:03,952 WARN r.e.i.DefaultProductionErrorHandler [ratpack-compute-1-7] Default production error handler used to render server error, please add a ratpack.error.ServerErrorHandler instance to your application (method: HEAD, uri: /versions)
2015-03-16T11:00:03.953178+00:00 app[web.1]:  java.lang.RuntimeException: Not an array response from https://api.github.com/repos/ratpack/ratpack/milestones?state=closed&sort=due_date&per_page=100
2015-03-16T11:00:03.953183+00:00 app[web.1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-03-16T11:00:03.953179+00:00 app[web.1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-03-16T11:00:03.953181+00:00 app[web.1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2015-03-16T11:00:03.953205+00:00 app[web.1]: 	at ratpack.site.github.GithubRequester$_getPage_closure4.doCall(GithubRequester.groovy:64)
2015-03-16T11:00:03.953206+00:00 app[web.1]: 	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
2015-03-16T11:00:03.953211+00:00 app[web.1]: 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
2015-03-16T11:00:03.953204+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
2015-03-16T11:00:03.953200+00:00 app[web.1]: 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
2015-03-16T11:00:03.953201+00:00 app[web.1]: 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
2015-03-16T11:00:03.953203+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
2015-03-16T11:00:03.953209+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-03-16T11:00:03.953210+00:00 app[web.1]: 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
2015-03-16T11:00:03.953212+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
2015-03-16T11:00:03.953184+00:00 app[web.1]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
2015-03-16T11:00:03.953215+00:00 app[web.1]: 	at groovy.lang.Closure.call(Closure.java:423)
2015-03-16T11:00:03.953216+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51)
2015-03-16T11:00:03.953207+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-03-16T11:00:03.953220+00:00 app[web.1]: 	at rx.Observable$31.onNext(Observable.java:7139)
2015-03-16T11:00:03.953219+00:00 app[web.1]: 	at com.sun.proxy.$Proxy48.call(Unknown Source)
2015-03-16T11:00:03.953218+00:00 app[web.1]: 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:103)
2015-03-16T11:00:03.953214+00:00 app[web.1]: 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
2015-03-16T11:00:03.953224+00:00 app[web.1]: 	at ratpack.rx.RxRatpack.lambda$null$0(RxRatpack.java:146)
2015-03-16T11:00:03.953229+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecControl$4.lambda$success$71(DefaultExecControl.java:209)
2015-03-16T11:00:03.953240+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle.lambda$complete$78(ExecutionBacking.java:119)
2015-03-16T11:00:03.953221+00:00 app[web.1]: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
2015-03-16T11:00:03.953228+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultPromise$ValuePassThru.success(DefaultPromise.java:285)
2015-03-16T11:00:03.953230+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecControl$4$$Lambda$175/513242741.execute(Unknown Source)
2015-03-16T11:00:03.953225+00:00 app[web.1]: 	at ratpack.rx.RxRatpack$$Lambda$169/259548866.execute(Unknown Source)
2015-03-16T11:00:03.953226+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:51)
2015-03-16T11:00:03.953242+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking.intercept(ExecutionBacking.java:226)
2015-03-16T11:00:03.953223+00:00 app[web.1]: 	at ratpack.rx.RxRatpack$ExecutionBackedSubscriber.onNext(RxRatpack.java:505)
2015-03-16T11:00:03.953241+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle$$Lambda$176/41268850.execute(Unknown Source)
2015-03-16T11:00:03.953247+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle.complete(ExecutionBacking.java:117)
2015-03-16T11:00:03.953245+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking.access$000(ExecutionBacking.java:32)
2015-03-16T11:00:03.953251+00:00 app[web.1]: 	at ratpack.http.client.internal.ContentAggregatingRequestAction$1.channelRead0(ContentAggregatingRequestAction.java:58)
2015-03-16T11:00:03.953243+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking.drain(ExecutionBacking.java:179)
2015-03-16T11:00:03.953267+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-16T11:00:03.953250+00:00 app[web.1]: 	at ratpack.http.client.internal.RequestActionSupport.success(RequestActionSupport.java:205)
2015-03-16T11:00:03.953248+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecControl$4.success(DefaultExecControl.java:209)
2015-03-16T11:00:03.953264+00:00 app[web.1]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2015-03-16T11:00:03.953252+00:00 app[web.1]: 	at ratpack.http.client.internal.ContentAggregatingRequestAction$1.channelRead0(ContentAggregatingRequestAction.java:49)
2015-03-16T11:00:03.953276+00:00 app[we
b.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-16T11:00:03.953282+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:315)
2015-03-16T11:00:03.953263+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-16T11:00:03.953255+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-16T11:00:03.953246+00:00 app[web.1]: 	at ratpack.exec.internal.ExecutionBacking$StreamHandle.streamEvent(ExecutionBacking.java:127)
2015-03-16T11:00:03.953273+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-16T11:00:03.953268+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-16T11:00:03.953278+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-16T11:00:03.953256+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-16T11:00:03.953254+00:00 app[web.1]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2015-03-16T11:00:03.953291+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
2015-03-16T11:00:03.953300+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745)
2015-03-16T11:00:03.953295+00:00 app[web.1]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
2015-03-16T11:00:03.953270+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-16T11:00:03.953274+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
2015-03-16T11:00:03.953265+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-16T11:00:03.953272+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-16T11:00:03.953275+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-16T11:00:03.953284+00:00 app[web.1]: 	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
2015-03-16T11:00:03.953298+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory$$Lambda$120/1956602275.run(Unknown Source)
2015-03-16T11:00:03.953288+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:947)
2015-03-16T11:00:03.953299+00:00 app[web.1]: 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-03-16T11:00:03.953279+00:00 app[web.1]: 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1044)
2015-03-16T11:00:03.953283+00:00 app[web.1]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:229)
2015-03-16T11:00:03.953285+00:00 app[web.1]: 	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
2015-03-16T11:00:03.953286+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
2015-03-16T11:00:03.953296+00:00 app[web.1]: 	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$55(DefaultExecController.java:82)
2015-03-16T11:00:03.953290+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
2015-03-16T11:00:03.953293+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
2015-03-16T11:00:03.953301+00:00 app[web.1]: 
2015-03-16T11:00:03.953269+00:00 app[web.1]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
2015-03-16T11:00:03.953280+00:00 app[web.1]: 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:929)
2015-03-16T11:00:03.953289+00:00 app[web.1]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
2015-03-16T11:00:03.953294+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
```
