### ISSUE TITLE
Lazybones template needs a newer springloaded version

### ISSUE THREAD

**Issue by saanvik** [ratpack/ratpack#654]
The current Lazybones template referred to in the manual runs, but with a bunch of errors like the following:

***
Apr 23, 2015 3:06:27 PM org.springsource.loaded.agent.SpringLoadedPreProcessor preProcess
SEVERE: Unexpected problem transforming call sites
java.lang.IllegalStateException: Unexpected problem processing bytes for class
	at org.springsource.loaded.ConstantPoolChecker2.readConstantPool(ConstantPoolChecker2.java:196)
	at org.springsource.loaded.ConstantPoolChecker2.<init>(ConstantPoolChecker2.java:128)
	at org.springsource.loaded.ConstantPoolChecker2.getReferences(ConstantPoolChecker2.java:102)
	at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:300)
	at org.springsource.loaded.MethodInvokerRewriter.rewriteUsingCache(MethodInvokerRewriter.java:156)
	at org.springsource.loaded.TypeRegistry.methodCallRewriteUseCacheIfAvailable(TypeRegistry.java:828)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:321)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:102)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ratpack.groovy.GroovyRatpackMain.main(GroovyRatpackMain.java:37)
Caused by: java.lang.IllegalStateException: Entry: 16 18
	at orgsource.loaded.ConstantPoolChecker2.processConstantPoolEntry(ConstantPoolChecker2.java:335)
	at org.springsource.loaded.ConstantPoolChecker2.readConstantPool(ConstantPoolChecker2.java:186)
	... 22 more

******

This appears to be due to the version of springloaded being used.

The current template is 

springloaded "org.springframework:springloaded:1.2.1.RELEASE"

replacing it with the following:

springloaded "org.springframework:springloaded:1.2.3.RELEASE"

makes the errors go away.

Environment: Mac, OSX 10.10, using the included gradlew

**Comment by rhart** [comment]
This version isn't currently in maven central and would mean taking it from the spring repo https://github.com/spring-projects/spring-loaded/issues/115

I'll get this in for the next release

**Comment by saanvik** [comment]
Great.  Quick question for you - was the choice to name the main groovy file Ratpack.groovy intentional?  Throughout the manual the filename is  lower-case r ("ratpack.groovy").

**Comment by alkemist** [comment]
Either works. The intention was to use lowercase, but there was a bug with intellij and classes beginning with lower case letters that forced us to use the R convention.

My personal preference is to name Groovy _scripts_ with an initial lower case letter, classes with an upper.
