### ISSUE TITLE
Ratpack can't handle proxy authentication over SSL

### ISSUE THREAD

**Issue by pledbrook** [ratpack/ratpack#918]
I tried creating a proxy that runs over SSL, but whenever a client tries to access an HTTPS URL, the Ratpack app throws this exception:

    [ratpack-compute-1-2] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
    io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 434f4e4e45435420617573342e6d6f7a696c6c612e6f72673a34343320485454502f312e310d0a557365722d4167656e743a204d6f7a696c6c612f352e3020284d6163696e746f73683b20496e74656c204d6163204f5320582031302e31313b2072763a34302e3029204765636b6f2f32303130303130312046697265666f782f34302e300d0a50726f78792d436f6e6e656374696f6e3a206b6565702d616c6976650d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a486f73743a20617573342e6d6f7a696c6c612e6f72673a3434330d0a0d0a
    	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:980)
    	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:950)
    	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:113)
    	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory$$Lambda$116/2111882926.run(Unknown Source)
    	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    	at java.lang.Thread.run(Thread.java:745)

I don't think this is a high priority, since it seems to be an edge case. And I quite frankly have no idea what the problem is. Perhaps Ratpack needs to be able to handle HTTP & HTTPS at the same time? Maybe it's an issue with Netty?

To reproduce, just run the Ratpack application [from here](https://dl.dropboxusercontent.com/u/29802534/Bugs/ratpack-proxy.zip), configure Firefox or some other browser with localhost:5050 as the HTTPS proxy, and then access https://grails.org/ .

**Comment by pledbrook** [comment]
OK, the proxy shouldn't be running on HTTPS. The correct procedure is to handle a `CONNECT` request over HTTP to set up a TCP tunnel to the target server. The proxy then shoves bytes from the client to the server and back again.

I think the proxy has to wrap the TCP responses in HTTP responses before sending the data back to the client, but I'm not sure. Something else for me to work out.

**Comment by rhart** [comment]
I haven't looked at your code yet but have tried some proxy work with ratpack before.  I can't remember if I got https working but I'll try and dig out my stuff.

If you're looking at doing this in Netty you might find this PR useful https://github.com/netty/netty/pull/2817 and this test case https://github.com/netty/netty/blob/add7efc2d4f818bfb02cef7a34c701827e83ddf7/handler-proxy/src/test/java/io/netty/handler/proxy/ProxyHandlerTest.java#L284
