### ISSUE TITLE
Getting NPE with ratpack.publicAddress in 1.3.3

### ISSUE THREAD

**Issue by ysb33r** [ratpack/ratpack#989]
Passing either `-Dratpack.publicAddress` or setting environment variable `RATPACK_PUBLIC_ADDRESS` in Ratpack 1.3.3 yields NPE.

The stack trace is 

```
Exception in thread "main" java.lang.NullPointerException

at ratpack.server.internal.ServerEnvironment.parseUri(ServerEnvironment.java:116)
	at ratpack.server.internal.ServerEnvironment.lambda$getPublicAddress$12(ServerEnvironment.java:103)
	at ratpack.server.internal.ServerEnvironment$$Lambda$74/238564722.get(Unknown Source)
	at ratpack.server.internal.ServerEnvironment$$Lambda$8/1349277854.apply(Unknown Source)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.getNext(Iterators.java:865)
	at com.google.common.collect.Iterators.find(Iterators.java:733)
	at com.google.common.collect.Iterables.find(Iterables.java:660)
	at ratpack.server.internal.ServerEnvironment.get(ServerEnvironment.java:62)
	at ratpack.server.internal.ServerEnvironment.getPublicAddress(ServerEnvironment.java:101)
	at ratpack.server.internal.DefaultServerConfigBuilder$ConfigModule.<init>(DefaultServerConfigBuilder.java:392)
	at ratpack.server.internal.DefaultServerConfigBuilder.build(DefaultServerConfigBuilder.java:360)
	at ratpack.server.internal.RatpackServerDefinition.lambda$build$0(RatpackServerDefinition.java:44)
	at ratpack.server.internal.RatpackServerDefinition$$Lambda$77/802771878.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at ratpack.server.internal.RatpackServerDefinition.build(RatpackServerDefinition.java:44)
	at ratpack.server.internal.DefaultRatpackServer.lambda$buildUserDefinition$3(DefaultRatpackServer.java:191)
	at ratpack.server.internal.DefaultRatpackServer$$Lambda$18/607635164.create(Unknown Source)
	at ratpack.impose.Impositions.impose(Impositions.java:117)
	at ratpack.server.internal.DefaultRatpackServer.buildUserDefinition(DefaultRatpackServer.java:187)
	at ratpack.server.internal.DefaultRatpackServer.start(DefaultRatpackServer.java:106)
	at ratpack.server.RatpackServer.start(RatpackServer.java:90)
	at ratpack.groovy.GroovyRatpackMain.main(GroovyRatpackMain.java:38)
```

**Comment by alkemist** [comment]
What value are you setting?

**Comment by ysb33r** [comment]
`-Dratpack.publicAddress=192.168.1.151` or

via gradle 

```groovy
run {
  systemProperties ratpack.publicAddress : '192.168.1.151'
}
```

**Comment by rhart** [comment]
@ysb33r you need to include a scheme with the ip address.  We check that it's http or https, in your example it is null
https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/server/internal/ServerEnvironment.java#L116

**Comment by alkemist** [comment]
We should change our logic to default to HTTP given an URL without an explicit protocol.

**Comment by rhart** [comment]
I'll make the change.

**Comment by ysb33r** [comment]
> you need to include a scheme with the ip address. We check that it's http or https, in your example it is null

Thanks for that. I'll mention the fact that it said `publicAddress`, not `publicUrl` let me to think it is only an IP address.

**Comment by ysb33r** [comment]
Mmm.. having tested it with `-Dratpack.publicAddress=http://1.2.3.4` it seems to stick to `localhost`. (`-Dratpack.port=50050` is recognised correctly).

**Comment by ysb33r** [comment]
I am terribly confused now as even if I do 

```groovy
ratpack {
  serverConfig {
    port 50050   // <-- Works
    isDevelopment false // <-- Works
    publicAddress 'http://1.2.3.4'.toURI()  // <-- Does not work
  }
}
```
it still uses `localhost`.
